#include "overlay_menu.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <SDL.h>

#include "config.h"
#include "features.h"
#include "zelda_rtl.h"

extern Config g_config;

// Generated by tools/genfont.py -- do not edit by hand.
// 8 rows per glyph, bit 0 = leftmost pixel. ASCII 32..90.
static const uint8 kMenuFont[59][8] = {
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // space
  { 0x04, 0x04, 0x04, 0x04, 0x00, 0x04, 0x00, 0x00 }, // !
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // "
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // #
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // $
  { 0x11, 0x11, 0x08, 0x04, 0x02, 0x11, 0x11, 0x00 }, // %
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // &
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // '
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // (
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // )
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // *
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // +
  { 0x00, 0x00, 0x00, 0x00, 0x04, 0x04, 0x02, 0x00 }, // ,
  { 0x00, 0x00, 0x00, 0x1f, 0x00, 0x00, 0x00, 0x00 }, // -
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00 }, // .
  { 0x10, 0x08, 0x04, 0x04, 0x02, 0x01, 0x01, 0x00 }, // /
  { 0x0e, 0x11, 0x19, 0x15, 0x13, 0x11, 0x0e, 0x00 }, // 0
  { 0x04, 0x06, 0x04, 0x04, 0x04, 0x04, 0x0e, 0x00 }, // 1
  { 0x0e, 0x11, 0x10, 0x08, 0x04, 0x02, 0x1f, 0x00 }, // 2
  { 0x0f, 0x10, 0x10, 0x0c, 0x10, 0x11, 0x0e, 0x00 }, // 3
  { 0x08, 0x0c, 0x0a, 0x09, 0x1f, 0x08, 0x08, 0x00 }, // 4
  { 0x1f, 0x01, 0x0f, 0x10, 0x10, 0x11, 0x0e, 0x00 }, // 5
  { 0x0c, 0x02, 0x01, 0x0f, 0x11, 0x11, 0x0e, 0x00 }, // 6
  { 0x1f, 0x11, 0x10, 0x08, 0x04, 0x04, 0x04, 0x00 }, // 7
  { 0x0e, 0x11, 0x11, 0x0e, 0x11, 0x11, 0x0e, 0x00 }, // 8
  { 0x0e, 0x11, 0x11, 0x1e, 0x10, 0x08, 0x06, 0x00 }, // 9
  { 0x00, 0x04, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00 }, // :
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // ;
  { 0x08, 0x04, 0x02, 0x01, 0x02, 0x04, 0x08, 0x00 }, // <
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // =
  { 0x02, 0x04, 0x08, 0x10, 0x08, 0x04, 0x02, 0x00 }, // >
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // ?
  { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // @
  { 0x0e, 0x11, 0x11, 0x1f, 0x11, 0x11, 0x11, 0x00 }, // A
  { 0x0f, 0x11, 0x11, 0x0f, 0x11, 0x11, 0x0f, 0x00 }, // B
  { 0x0e, 0x11, 0x01, 0x01, 0x01, 0x11, 0x0e, 0x00 }, // C
  { 0x07, 0x09, 0x11, 0x11, 0x11, 0x09, 0x07, 0x00 }, // D
  { 0x1f, 0x01, 0x01, 0x0f, 0x01, 0x01, 0x1f, 0x00 }, // E
  { 0x1f, 0x01, 0x01, 0x0f, 0x01, 0x01, 0x01, 0x00 }, // F
  { 0x0e, 0x11, 0x01, 0x1d, 0x11, 0x11, 0x1e, 0x00 }, // G
  { 0x11, 0x11, 0x11, 0x1f, 0x11, 0x11, 0x11, 0x00 }, // H
  { 0x0e, 0x04, 0x04, 0x04, 0x04, 0x04, 0x0e, 0x00 }, // I
  { 0x18, 0x10, 0x10, 0x10, 0x11, 0x11, 0x0e, 0x00 }, // J
  { 0x11, 0x09, 0x05, 0x03, 0x05, 0x09, 0x11, 0x00 }, // K
  { 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x1f, 0x00 }, // L
  { 0x11, 0x1b, 0x15, 0x15, 0x11, 0x11, 0x11, 0x00 }, // M
  { 0x11, 0x13, 0x15, 0x19, 0x11, 0x11, 0x11, 0x00 }, // N
  { 0x0e, 0x11, 0x11, 0x11, 0x11, 0x11, 0x0e, 0x00 }, // O
  { 0x0f, 0x11, 0x11, 0x0f, 0x01, 0x01, 0x01, 0x00 }, // P
  { 0x0e, 0x11, 0x11, 0x11, 0x15, 0x09, 0x16, 0x00 }, // Q
  { 0x0f, 0x11, 0x11, 0x0f, 0x05, 0x09, 0x11, 0x00 }, // R
  { 0x1e, 0x01, 0x01, 0x0e, 0x10, 0x10, 0x0f, 0x00 }, // S
  { 0x1f, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x00 }, // T
  { 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x0e, 0x00 }, // U
  { 0x11, 0x11, 0x11, 0x11, 0x11, 0x0a, 0x04, 0x00 }, // V
  { 0x11, 0x11, 0x11, 0x15, 0x15, 0x1b, 0x11, 0x00 }, // W
  { 0x11, 0x11, 0x0a, 0x04, 0x0a, 0x11, 0x11, 0x00 }, // X
  { 0x11, 0x11, 0x0a, 0x04, 0x04, 0x04, 0x04, 0x00 }, // Y
  { 0x1f, 0x10, 0x08, 0x04, 0x02, 0x01, 0x1f, 0x00 }, // Z
};

static bool g_open;
static int g_cursor_row;

// Geometry of the last drawn panel, in normalized window coordinates, so touch
// input can be hit-tested against it without knowing the buffer size.
static float g_panel_x0, g_panel_y0, g_panel_x1, g_panel_y1;
static float g_rows_y0, g_row_h;

enum ItemKind { kToggle, kChoice };

typedef struct MenuItem {
  const char *label;     // English
  const char *label_es;
  enum ItemKind kind;
  int action;           // if non-zero, the row runs this action
  uint8 *cfg;           // the g_config field it drives
  uint32 feature_bit;   // if non-zero, also toggles this features0 bit
  const char *const *choices;     // English
  const char *const *choices_es;
  int choice_count;
  const uint8 *choice_values;
} MenuItem;

static const char *const kTurboNames[] = { "ORIGINAL", "X2", "X3", "X4", "X5" };
static const uint8 kTurboValues[] = { 0, 2, 3, 4, 5 };
static const char *const kStickNames[] = { "DPAD", "STICK" };
static const char *const kStickNamesEs[] = { "CRUZ", "STICK" };
static const uint8 kStickValues[] = { 0, 1 };
static const char *const kTouchNames[] = { "AUTO", "ON", "OFF" };
static const char *const kTouchNamesEs[] = { "AUTO", "SI", "NO" };
static const uint8 kTouchValues[] = { 0, 1, 2 };
static const char *const kLangNames[] = { "ENGLISH", "ESPANOL" };
static const uint8 kLangValues[] = { 0, 1 };

static MenuItem g_items[] = {
  { "LANGUAGE", "IDIOMA", kChoice, 0, &g_config.menu_language, 0,
    kLangNames, kLangNames, 2, kLangValues },
  { "LOCKED CAMERA", "CAMARA ANCLADA", kToggle, 0,
    &g_config.widescreen_edge_mode, 0, NULL, NULL, 0, NULL },
  { "TURBO SPEED", "VELOCIDAD TURBO", kChoice, 0, &g_config.turbo_speed, 0,
    kTurboNames, kTurboNames, 5, kTurboValues },
  { "TOUCH BUTTONS", "BOTONES TACTIL", kChoice, 0, &g_config.touch_controls, 0,
    kTouchNames, kTouchNamesEs, 3, kTouchValues },
  { "D-PAD STYLE", "DIRECCIONAL", kChoice, 0, &g_config.touch_stick, 0,
    kStickNames, kStickNamesEs, 2, kStickValues },
  { "MOVE BUTTONS", "MOVER BOTONES", kToggle, kMenuActionMoveButtons,
    NULL, 0, NULL, NULL, 0, NULL },
  { "RESET LAYOUT", "RESET POSICION", kToggle, kMenuActionResetButtons,
    NULL, 0, NULL, NULL, 0, NULL },
  { "SAVE STATE", "GUARDAR PARTIDA", kToggle, kMenuActionSaveState,
    NULL, 0, NULL, NULL, 0, NULL },
  { "LOAD STATE", "CARGAR PARTIDA", kToggle, kMenuActionLoadState,
    NULL, 0, NULL, NULL, 0, NULL },
  { "ITEMS ON L/R", "ITEMS EN L/R", kToggle, 0, NULL, kFeatures0_SwitchLR,
    NULL, NULL, 0, NULL },
  { "TURN WHILE DASHING", "GIRAR AL CORRER", kToggle, 0, NULL,
    kFeatures0_TurnWhileDashing, NULL, NULL, 0, NULL },
  { "MORE BOMBS", "MAS BOMBAS", kToggle, 0, NULL, kFeatures0_MoreActiveBombs,
    NULL, NULL, 0, NULL },
  { "MORE RUPEES", "MAS RUPIAS", kToggle, 0, NULL, kFeatures0_CarryMoreRupees,
    NULL, NULL, 0, NULL },
  { "BREAK POTS", "ROMPER OLLAS", kToggle, 0, NULL,
    kFeatures0_BreakPotsWithSword, NULL, NULL, 0, NULL },
  { "BUG FIXES", "ARREGLOS BUGS", kToggle, 0, NULL, kFeatures0_MiscBugFixes,
    NULL, NULL, 0, NULL },
};
#define kItemCount ((int)(sizeof(g_items) / sizeof(g_items[0])))
#define kSaveRow kItemCount
#define kRowCount (kItemCount + 1)

// Returns the string for the language the menu is currently set to.
const char *OverlayMenu_Text(const char *en, const char *es) {
  return g_config.menu_language ? es : en;
}
#define T(en, es) OverlayMenu_Text(en, es)

bool OverlayMenu_IsOpen(void) { return g_open; }

// ---------------------------------------------------------------------------
// Persistence: rewrites only the keys that changed, preserving the .ini's
// comments and ordering. A key that doesn't exist yet is appended at the end.
// ---------------------------------------------------------------------------
static bool KeyMatches(const char *line, const char *key) {
  size_t n = strlen(key);
  if (strncmp(line, key, n) != 0)
    return false;
  const char *p = line + n;
  while (*p == ' ' || *p == '\t') p++;
  return *p == '=';
}

// The Android port does not use the current directory: all its files live under
// SDL_AndroidGetExternalStoragePath(). The path has to be resolved the same way
// the rest of the engine does it, or we write somewhere nobody reads.
static void ResolvePath(char *out, size_t n, const char *name) {
  const char *dir = SDL_AndroidGetExternalStoragePath();
  if (dir && *dir)
    snprintf(out, n, "%s/%s", dir, name);
  else
    snprintf(out, n, "%s", name);
}

static void SaveConfig(void) {
  char ini_path[512], tmp_path[512];
  ResolvePath(ini_path, sizeof(ini_path), "zelda3.ini");
  ResolvePath(tmp_path, sizeof(tmp_path), "zelda3.ini.tmp");
  static const char *const kKeys[] = { "WidescreenEdgeMode", "TurboSpeed",
                                      "TouchStick", "TouchControls",
                                      "MenuLanguage" };
  enum { kKeyCount = 5 };
  char values[kKeyCount][32];
  snprintf(values[0], sizeof(values[0]), "%d", g_config.widescreen_edge_mode);
  snprintf(values[1], sizeof(values[1]), "%d", g_config.turbo_speed);
  snprintf(values[2], sizeof(values[2]), "%d", g_config.touch_stick);
  snprintf(values[3], sizeof(values[3]), "%d", g_config.touch_controls);
  snprintf(values[4], sizeof(values[4]), "%d", g_config.menu_language);

  FILE *in = fopen(ini_path, "rb");
  if (!in)
    return;
  fseek(in, 0, SEEK_END);
  long size = ftell(in);
  fseek(in, 0, SEEK_SET);
  if (size <= 0 || size > (16 << 20)) { fclose(in); return; }
  char *buf = (char *)malloc((size_t)size + 1);
  if (!buf) { fclose(in); return; }
  size_t got = fread(buf, 1, (size_t)size, in);
  fclose(in);
  buf[got] = 0;

  FILE *out = fopen(tmp_path, "wb");
  if (!out) { free(buf); return; }
  bool written[kKeyCount] = { false, false, false, false, false };
  char *line = buf;
  while (line && *line) {
    char *eol = strchr(line, '\n');
    if (eol) *eol = 0;
    int matched = -1;
    for (int k = 0; k < kKeyCount; k++) {
      if (!written[k] && KeyMatches(line, kKeys[k])) { matched = k; break; }
    }
    if (matched >= 0) {
      fprintf(out, "%s = %s\n", kKeys[matched], values[matched]);
      written[matched] = true;
    } else {
      fprintf(out, "%s\n", line);
    }
    line = eol ? eol + 1 : NULL;
  }
  for (int k = 0; k < kKeyCount; k++) {
    if (!written[k])
      fprintf(out, "%s = %s\n", kKeys[k], values[k]);
  }
  fclose(out);
  free(buf);
  remove(ini_path);
  rename(tmp_path, ini_path);
}

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------
static int ChoiceIndex(const MenuItem *it) {
  for (int i = 0; i < it->choice_count; i++)
    if (it->choice_values[i] == *it->cfg)
      return i;
  return 0;
}

static void ApplyEdgeMode(void) {
  ZeldaSetWidescreenEdgeMode(g_config.widescreen_edge_mode);
}

static void ChangeRow(int row, int delta) {
  if (row == kSaveRow) {
    if (delta != 0)
      SaveConfig();
    return;
  }
  MenuItem *it = &g_items[row];
  if (it->action) {
    // Close BEFORE running it: the action goes through HandleCommand, which
    // discards every input while the menu is still open.
    g_open = false;
    OverlayMenu_RunAction(it->action);
    return;
  }
  if (it->feature_bit) {
    // Feature bits are copied into enhanced_features0 every frame, so toggling
    // them here takes effect immediately.
    g_wanted_zelda_features ^= it->feature_bit;
    g_config.features0 = g_wanted_zelda_features;
    return;
  }
  if (it->kind == kToggle) {
    *it->cfg = *it->cfg ? 0 : 1;
  } else {
    int i = ChoiceIndex(it) + delta;
    if (i < 0) i = it->choice_count - 1;
    if (i >= it->choice_count) i = 0;
    *it->cfg = it->choice_values[i];
  }
  if (it->cfg == &g_config.widescreen_edge_mode)
    ApplyEdgeMode();
}

// One tap on a row selects it and advances it, which is the whole interaction:
// choices cycle and wrap, so any value is reachable without a second gesture.
bool OverlayMenu_HandleTouch(float x, float y) {
  if (!g_open)
    return false;
  if (x < g_panel_x0 || x > g_panel_x1 || y < g_panel_y0 || y > g_panel_y1) {
    // Tapping outside closes it. Without this there is no way out by touch: the
    // panel is centered and covers the MENU button that opened it.
    g_open = false;
    return true;
  }
  if (g_row_h <= 0.0f)
    return true;
  int row = (int)((y - g_rows_y0) / g_row_h);
  if (row < 0 || row >= kRowCount)
    return true;  // the title or the footer: swallowed, but does nothing
  g_cursor_row = row;
  ChangeRow(row, +1);
  return true;
}

void OverlayMenu_Toggle(void) {
  g_open = !g_open;
}

bool OverlayMenu_HandleCommand(uint32 cmd, bool pressed) {
  if (!g_open)
    return false;
  if (!pressed)
    return true;  // while open, the game receives nothing
  switch (cmd - kKeys_Controls) {
  case 0: g_cursor_row = (g_cursor_row + kRowCount - 1) % kRowCount; break;  // up
  case 1: g_cursor_row = (g_cursor_row + 1) % kRowCount; break;              // down
  case 2: ChangeRow(g_cursor_row, -1); break;                                // left
  case 3: ChangeRow(g_cursor_row, +1); break;                                // right
  case 6: ChangeRow(g_cursor_row, +1); break;                                // A
  case 7: g_open = false; break;                                             // B
  case 5: g_open = false; break;                                             // Start
  default: break;
  }
  return true;
}

// ---------------------------------------------------------------------------
// Dibujado
// ---------------------------------------------------------------------------
static void Blend(uint32 *p, uint32 color, int alpha) {
  uint32 d = *p;
  uint32 r = (((color >> 16) & 0xff) * alpha + ((d >> 16) & 0xff) * (255 - alpha)) / 255;
  uint32 g = (((color >> 8) & 0xff) * alpha + ((d >> 8) & 0xff) * (255 - alpha)) / 255;
  uint32 b = ((color & 0xff) * alpha + (d & 0xff) * (255 - alpha)) / 255;
  *p = (r << 16) | (g << 8) | b;
}

void OverlayDraw_Rect(uint8 *pixels, size_t pitch, int w, int h,
                     int x0, int y0, int x1, int y1, uint32 color, int alpha) {
  if (x0 < 0) x0 = 0;
  if (y0 < 0) y0 = 0;
  if (x1 > w) x1 = w;
  if (y1 > h) y1 = h;
  for (int y = y0; y < y1; y++) {
    uint32 *row = (uint32 *)(pixels + (size_t)y * pitch);
    for (int x = x0; x < x1; x++)
      Blend(&row[x], color, alpha);
  }
}

static int DrawTextInner(uint8 *pixels, size_t pitch, int w, int h,
                    int x, int y, const char *s, uint32 color, int scale) {
  for (; *s; s++) {
    int c = (unsigned char)*s;
    if (c >= 'a' && c <= 'z')
      c -= 32;
    if (c < 32 || c > 90)
      c = 32;
    const uint8 *glyph = kMenuFont[c - 32];
    for (int gy = 0; gy < 8; gy++) {
      int bits = glyph[gy];
      for (int gx = 0; bits; gx++, bits >>= 1) {
        if (!(bits & 1))
          continue;
        OverlayDraw_Rect(pixels, pitch, w, h, x + gx * scale, y + gy * scale,
                 x + (gx + 1) * scale, y + (gy + 1) * scale, color, 255);
      }
    }
    x += 6 * scale;
  }
  return x;
}

void OverlayMenu_Draw(uint8 *pixels, size_t pitch, int width, int height) {
  if (!g_open)
    return;
  // Scale is derived from the buffer height so the menu reads the same at
  // native resolution and with the upsampled Mode7 renderer.
  int scale = height / 200;
  if (scale < 1) scale = 1;

  int line_h = 11 * scale;
  int panel_w = 172 * scale;
  int panel_h = (kRowCount + 3) * line_h;
  int x0 = (width - panel_w) / 2;
  int y0 = (height - panel_h) / 2;

  OverlayDraw_Rect(pixels, pitch, width, height, x0, y0, x0 + panel_w, y0 + panel_h,
           0x101018, 220);
  OverlayDraw_Rect(pixels, pitch, width, height, x0, y0, x0 + panel_w, y0 + scale,
           0xf0d060, 255);
  OverlayDraw_Rect(pixels, pitch, width, height, x0, y0 + panel_h - scale,
           x0 + panel_w, y0 + panel_h, 0xf0d060, 255);

  g_panel_x0 = (float)x0 / width;
  g_panel_x1 = (float)(x0 + panel_w) / width;
  g_panel_y0 = (float)y0 / height;
  g_panel_y1 = (float)(y0 + panel_h) / height;
  g_row_h = (float)line_h / height;

  int tx = x0 + 6 * scale, ty = y0 + 3 * scale;
  DrawTextInner(pixels, pitch, width, height, tx, ty,
                T("SETTINGS", "AJUSTES"), 0xf0d060, scale);
  ty += line_h + 2 * scale;
  g_rows_y0 = (float)ty / height;

  char buf[64];
  for (int i = 0; i < kRowCount; i++) {
    bool sel = (i == g_cursor_row);
    if (sel)
      OverlayDraw_Rect(pixels, pitch, width, height, x0 + 2 * scale, ty - scale,
               x0 + panel_w - 2 * scale, ty + 9 * scale, 0x304060, 255);
    uint32 col = sel ? 0xffffff : 0xa0a0b0;
    if (i == kSaveRow) {
      DrawTextInner(pixels, pitch, width, height, tx, ty,
                    T("SAVE CONFIG", "GUARDAR CONFIG"), col, scale);
    } else {
      const MenuItem *it = &g_items[i];
      DrawTextInner(pixels, pitch, width, height, tx, ty,
                    T(it->label, it->label_es), col, scale);
      const char *val;
      if (it->action)
        val = "-";
      else if (it->feature_bit)
        val = (g_wanted_zelda_features & it->feature_bit) ? T("ON", "SI")
                                                         : T("OFF", "NO");
      else if (it->kind == kToggle)
        val = *it->cfg ? T("ON", "SI") : T("OFF", "NO");
      else {
        // Careful: these are arrays of strings, not strings. Running them
        // through T() picked the right array but returned a const char*, and
        // indexing that built a garbage pointer. Pick the array, then index.
        const char *const *names =
            g_config.menu_language ? it->choices_es : it->choices;
        val = names[ChoiceIndex(it)];
      }
      snprintf(buf, sizeof(buf), "%s", val);
      int vw = (int)strlen(buf) * 6 * scale;
      DrawTextInner(pixels, pitch, width, height,
               x0 + panel_w - 6 * scale - vw, ty, buf, col, scale);
    }
    ty += line_h;
  }
  DrawTextInner(pixels, pitch, width, height, tx, ty + scale,
                T("B OR TAP OUTSIDE", "B O TOCA FUERA"), 0x808090, scale);
}

void OverlayDraw_Text(uint8 *pixels, size_t pitch, int w, int h,
                      int x, int y, const char *s, uint32 color, int scale) {
  DrawTextInner(pixels, pitch, w, h, x, y, s, color, scale);
}
